language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE job_board_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: DtOx9fHBFjQ25WkINmO4yoQh/yZtsewz1i3LA2t25ccOgYCr/nCUo18uxTahJizBUWl6yGH7ztw4uuczuyHnFox2OlBYwPRpF1cFfQd89Jpu7XJumd2IPHZBHIGztzghlX5bYu1/A6n9EcO2pqo4ezQxHbrFZf4wWvrFXMlED/ukDBDZ2rMCPbTjj8MqB9NILXRzmluW2MmqNL563b1bKFVCrikgie98RFUx/6gMhoHkAeQ8QyJ9KK25IXOUt2MzZoTaUT8hThWmdQlEvLuyv4HiT6ZaIrdXMfcTrIMJiMDIVCRemwQqyjPEJlVS1/nJYy1CHbghnUXFNFdqD8VPWpdD2b9XkF4QA7OqH2kgEgQW8gw7T61j/h12NEPv9asKhWBVkRhvLcG1cbgKiotCBgJ4PgdkOphNLx4W0nCrlvZ3n9fssro6UfnPnJOHhQqO1+fJMjJm7y4Pdcdo1wtRlkP3TUrHQYrXvuHTfnAu6zm8D9/EAUZD4zMtmy96/Y+lur2KWcDQJgDLCebe8rPsfF6XsCGBjbo4hVF2I/qM8JB2IpL1s8lYPKEZ+xVNG6ZY5CNaF7bc5csQ9VjSclxLmBc5X35xHX9+65Md4Cl5qlTsbghbGdT4FCSRscigPTRoh2qkcLPpsSBmaWqhpXB4VULMkHx/sCl7YxAvFoxO6ss=
  app: dev-connection
  skip_cleanup: true
